[package]
name = "call"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
sip-syntax = { path = "../sip-syntax" }
sip-stack = { path = "../sip-stack" }
rtp = { path = "../rtp" }
media = { path = "../media" }

[dev-dependencies]
proptest = { workspace = true }
